[project]
name = "agri-ledger-network"
authors = []
description = ""
telemetry = false
requirements = []
[contracts.member-registry]
path = "contracts/member-registry.clar"
depends_on = []

[contracts.ledger-operations]
path = "contracts/ledger-operations.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
